package com.codewars.BasicSequencePractice;

public class SequenceSum {

    public static void main(String[] args) {
        int[] x =sumOfN(-4);
       for (int q :x){
           System.out.println(q);
       }
    }



    public static int[] sumOfN(int n) {
        int a = n>0?1:-1;
        int result =0;
        int[] results = new int[n*a+1];
        for (int i = 0; i < results.length; i++) {
            result = result+i ;
            results[i] = result * a;
        }
        return results; //Generated by die roll; guaranteed to be random
    }
}